version: 2
executorType: docker
containerInfo:
  - image: markfirmware/ultibo-docker2-x64@sha256:7207b75950d72e5dc1d2220df85655fa723f772dedc085025f1829ebea69e913
stages:
  build:
    workDir: ~/ultibo-workshop-predev
    steps:
      - type: checkout
      - name: Bootstrap
        type: shell
        command: source bootstrap.sh.source
      - name: Build and test
        type: shell
        command: export PATH=~/ultibo-workshop-predev/usubsystem:$PATH && u build
      - name: Save artifacts
        type: artifacts-store
        path: artifacts
        destination: ultibo-workshop
