version: 2
executorType: docker
containerInfo:
  - image: markfirmware/ultibo-docker-x64-v2
stages:
  build:
    workDir: ~/ultibo-workshop-predev
    steps:
      - type: checkout
      - name: Bootstrap
        type: shell
        command: source bootstrap.sh.source
      - name: Build and test
        type: shell
        command: export PATH=~/ultibo-workshop-predev/usubsystem:$PATH && u build
      - name: Save artifacts
        type: artifacts-store
        path: artifacts
        destination: ultibo-workshop
