version: 2
executorType: docker
containerInfo:
  - image: markfirmware/ultibo-docker2-x64@sha256:66586c5b04fca9e967157abfd1b3bbb96de3ff47757ccddd1e086e0e36f3605c
stages:
  build:
    workDir: ~/ultibo-workshop-predev
    steps:
      - type: checkout
      - name: Build and test
        type: shell
        command: source bootstrap.sh.source && u build
      - name: Save artifacts
        type: artifacts-store
        path: artifacts
        destination: ultibo-workshop
